SECRET_KEY = "01ec1e03b1de11b150cd16b4045a99d6463246589b51151cf06eba5acbd00a74"
API_BASE_URL = "https://angwa-backend.onrender.com"
FRONTEND_URL = "https://angwalive.streamlit.app/"
TURSO_URL = "https://angwadb-till.aws-eu-west-1.turso.io"
TURSO_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODEzODAxNzYsImlkIjoiMDE5ZWMxYTAtMDgwMS03NjEyLTllM2QtMDBiM2VjODVmMmQ4IiwicmlkIjoiYTQyOTE5OGQtZDk3YS00NzFjLThmOTktNWUxMmRjYmFlZTVjIn0.WhNJZoA55iVH2NMbgN7H6uEFTr96xR_3PpWniZL0nCawej8RgGt8YByVGduLVsg9CUfHJK3pJYvwm-XBEpEGCA"